update requirements
Rookout/tutorial-python pull request #49
Opened 2021-06-08 13:03 UTC by niryarden

I forked the flask-openTracing module (https://github.com/opentracing-contrib/python-flask) and pushed a little addition (https://github.com/Rookout/python-flask/commit/79637485c460bfa3865e5a491147a9dd3aeec905).

in this PR, I'm changing our tutorial-python app to use the fork instead of the original repo.

This means the tags our tracing context has will include the user's IP address (retrieved from Flask).
here a screenshot from rookout, notice the remote_addr tag. (in this case localhost, since that's where I tested it)

![image](https://user-images.githubusercontent.com/42871571/121187910-3ae6dc80-c871-11eb-8686-bacccea242aa.png)

2021-06-08 13:04 UTC, niryarden commented
/jira open task

2021-06-08 13:06 UTC, LiranLast approved these changes

2021-06-08 13:07 UTC, LiranLast requested changes
It might be better to store the IP as context instead of tag.

Tags get sent to tracing providers and may have privacy implications.

2021-06-09 07:22 UTC, niryarden commented
will not be in both the tags and the span context.
the spanContext is following the latest commit in the fork
the tag is because I found it it can be done from tutorial-python itself without adding it in the flask-openTracing fork

![image](https://user-images.githubusercontent.com/42871571/121310839-75ea1e00-c90c-11eb-9c67-fd2b0b27467d.png)
![image](https://user-images.githubusercontent.com/42871571/121310863-7bdfff00-c90c-11eb-88ad-c32dea3985a5.png)

2021-06-09 07:23 UTC, LiranLast commented on app.py
> +flask_tracer = FlaskTracer(initialize_tracer, True, app, ["remote_addr"])
Do you still want this?

2021-06-09 07:23 UTC, niryarden commented on app.py
> +flask_tracer = FlaskTracer(initialize_tracer, True, app, ["remote_addr"])
it's nice to have

2021-06-09 07:23 UTC, niryarden commented on app.py
> +flask_tracer = FlaskTracer(initialize_tracer, True, app, ["remote_addr"])
i can remove if you thing we should

2021-06-09 07:23 UTC, LiranLast commented on app.py
> +flask_tracer = FlaskTracer(initialize_tracer, True, app, ["remote_addr"])
That's kind of what we are trying to avoid :)

2021-06-09 07:25 UTC, niryarden commented on app.py
> +flask_tracer = FlaskTracer(initialize_tracer, True, app, ["remote_addr"])
done

2021-06-09 07:25 UTC, LiranLast approved these changes

2021-06-09 07:30 UTC, merged