remove sentry
Rookout/tutorial-python pull request #77
Opened 2023-09-10 08:32 UTC by ElDuderinos

2023-09-10 08:33 UTC, ElDuderinos commented
/jira open task

2023-09-10 09:04 UTC, Urook commented on app.py
> -sentry_sdk.init(
Dont we need to recalculate the hash of the file?

2023-09-10 10:27 UTC, ElDuderinos commented on app.py
> -sentry_sdk.init(
true true, fixed

2023-09-10 13:16 UTC, Urook requested changes

2023-09-10 13:16 UTC, Urook commented on app.py
> -from sentry_sdk.integrations.flask import FlaskIntegration
Oh no,
Just realized our e2es rely on things being in specific lines. So, removing lines will break e2es. Lets leave the removed lines empty insteqd of removing them?

2023-09-27 06:08 UTC, ElDuderinos commented on app.py
> -from sentry_sdk.integrations.flask import FlaskIntegration
@Urook ?

2023-09-27 07:43 UTC, Urook commented on app.py
> -from sentry_sdk.integrations.flask import FlaskIntegration
@ElDuderinos Yes, in profiling

2023-09-27 08:21 UTC, ElDuderinos commented on app.py
> -from sentry_sdk.integrations.flask import FlaskIntegration
Gotcha, done

2023-09-27 08:52 UTC, Urook requested changes

2023-09-27 08:52 UTC, Urook commented on app.py
>  import sentry_sdk
Why not remove this?

2023-09-27 08:58 UTC, ElDuderinos commented on app.py
>  import sentry_sdk
aha, sorry good catch, removed

2023-09-27 09:26 UTC, Urook approved these changes

2023-09-27 09:26 UTC, merged